### ISSUE TITLE
Error not handled if cannot connect to local boinc instance

### ISSUE THREAD

**Issue by HeyMerlin** [makeasnek/FindTheMag2#17]
```
piadm@labpi1:~/FTM2/FindTheMag2 $ python main.py 
Gridcoin data dir does not appear to exist. If you have it in a non-standard location, please edit config.py so we know where to look
Press enter to continue or CTRL+C to quit
Traceback (most recent call last):
  File "/home/piadm/FTM2/FindTheMag2/main.py", line 2524, in <module>
    rpc_client = loop.run_until_complete(setup_connection(boinc_ip,boinc_password,boinc_port)) # setup BOINC RPC connection
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/piadm/FTM2/FindTheMag2/main.py", line 277, in setup_connection
    rpc_client = await init_rpc_client(boinc_ip, boinc_password, port=port)
  File "/home/piadm/FTM2/FindTheMag2/libs/pyboinc/rpc_client.py", line 31, in init_rpc_client
    await c.connect()
  File "/home/piadm/FTM2/FindTheMag2/libs/pyboinc/rpc_client.py", line 57, in connect
    await self._raw_client.connect()
  File "/home/piadm/FTM2/FindTheMag2/libs/pyboinc/_raw_client.py", line 35, in connect
    self._reader, self._writer = await asyncio.open_connection(self.host, self.port, family=AF_INET, limit=1024*5000)
  File "/usr/lib/python3.9/asyncio/streams.py", line 52, in open_connection
    transport, _ = await loop.create_connection(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 1056, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.9/asyncio/base_events.py", line 1041, in create_connection
    sock = await self._connect_sock(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 955, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect
    return await fut
  File "/usr/lib/python3.9/asyncio/selector_events.py", line 537, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('127.0.0.1', 31416)
```

- Restarted the Pi  after it lost network connectivity. 
- Connected via ssh, and launched FTM
- FTM crashed when the connection to the local boinc client failed

FTM should handle this error gracefully rather than just crashing.

Started FTM again about a minute later and it launched fine. I suspect that as this is a Pi3 that the boinc client was not up and running when I launched FTM the first time.

**Comment by HeyMerlin** [comment]
Should have mentioned that I'm running the FTM code I pulled on 2023-04-21.

**Comment by makeasnek** [comment]
Thank you for the bug report, fixed!
