### ISSUE TITLE
FTM 3.1 Crashing when trying to parse coinmarketcap price

### ISSUE THREAD

**Issue by APCBoston** [makeasnek/FindTheMag2#44]
``` Traceback (most recent call last):
  File "/usr/lib/python3.10/pdb.py", line 1723, in main
    pdb._runscript(mainpyfile)
  File "/usr/lib/python3.10/pdb.py", line 1583, in _runscript
    self.run(statement)
  File "/usr/lib/python3.10/bdb.py", line 598, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/home/andy/development/FindTheMag2-3.1/main.py", line 5038, in <module>
    boinc_loop(False, rpc_client)
  File "/home/andy/development/FindTheMag2-3.1/main.py", line 4011, in boinc_loop
    grc_price = get_grc_price()
  File "/home/andy/development/FindTheMag2-3.1/main.py", line 1011, in get_grc_price
    answer = float(regex_result.group(2))
ValueError: could not convert string to float: '0,'
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> /home/andy/development/FindTheMag2-3.1/main.py(1011)get_grc_price()
-> answer = float(regex_result.group(2))
(Pdb) url
'https://coinmarketcap.com/currencies/gridcoin/'
(Pdb) regex_result.group()
'"low24h":0,'
```

**Comment by makeasnek** [comment]
Thank you for the bug report! Does this consistently happen or just sometimes? Can you let me know:
- Your version of FTM
- Your version of python
You can e-mail a debug log to makeasnek@gmail.com, it automatically includes that info.

**Comment by makeasnek** [comment]
Fixed with new release.
