### ISSUE TITLE
Receiving this error on PC

### ISSUE THREAD

**Issue by JonathanEdMoore** [makeasnek/FindTheMag2#8]
```
Traceback (most recent call last):
  File "C:\Users\jmjon\FindTheMag2\main.py", line 2552, in <module>
    combined_stats,final_project_weights,total_preferred_weight,total_mining_weight,dev_project_weights=generate_stats(APPROVED_PROJECT_URLS=APPROVED_PROJECT_URLS,preferred_projects=preferred_projects,ignored_projects=ignored_projects,quiet=True,mag_ratios=mag_ratios)
                                                                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jmjon\FindTheMag2\main.py", line 1176, in generate_stats
    combined_stats = config_files_to_stats(boinc_data_dir)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jmjon\FindTheMag2\main.py", line 807, in config_files_to_stats
    credithistorylist = credit_history_file_to_list(credit_history_file)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jmjon\FindTheMag2\main.py", line 752, in credit_history_file_to_list
    parsed = xmltodict.parse(f.read())
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jmjon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\xmltodict.py", line 378, in parse
    parser.Parse(xml_input, True)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 0
```

**Comment by JonathanEdMoore** [comment]
I resolved this error.
